name: so_vuon
description: 돈을 심고, 미래를 키우다 - Plant your money. Grow your future.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.1

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^5.0.0
  firebase_analytics: ^12.0.2
  cloud_firestore: ^6.0.2
  cloud_functions: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0

  # Social Login
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

  # UI & Animation
  lottie: ^3.3.2
  fl_chart: ^1.1.1
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Routing
  go_router: ^16.2.4

  # Utilities
  intl: ^0.20.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.2
  csv: ^6.0.0
  file_picker: ^8.0.0
  share_plus: ^9.0.0

  # Security
  local_auth: ^2.2.0

  # Revenue
  purchases_flutter: ^6.27.0
  google_mobile_ads: ^5.1.0
  path_provider: ^2.1.5

  # Notifications
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
